name: Backlog Issue Sync
description: Sync Backlog issues with GitHub issues
author: hninu

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  backlog-host:
    description: 'Backlog host name (例: xxxxx.backlog.jp)'
    required: true
  backlog-api-key:
    description: 'Backlog API key'
    required: true
  backlog-project-key:
    description: 'Backlog project ID or key'
    required: true
  backlog-issue-type:
    description: 'Backlog issue type ID or name'
    required: true
  backlog-priority:
    description: 'Backlog priority ID or name'
    required: true
  backlog-initial-status:
    description: 'Backlog initial status ID or name (status applied to new issues when first created)'
    required: true
  backlog-completed-status:
    description: 'Backlog completed status ID or name (status applied when closing issues)'
    required: true
  backlog-summary-prefix:
    description: 'Optional prefix to add to the Backlog issue summary'
    required: false
  github-token:
    description: 'GitHub token (e.g. ${{ secrets.GITHUB_TOKEN }})'
    required: true

runs:
  using: node20
  main: dist/index.js
