name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install Dependencies
        id: pnpm-ci
        run: pnpm install --frozen-lockfile

      - name: Check
        id: pnpm-check
        run: pnpm run check

      # - name: Test
      #   id: pnpm-ci-test
      #   run: pnpm run ci-test


